import time
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By

class Test_soulwebsite:

    def automate(self):
        driver = webdriver.Firefox()
        driver.maximize_window()
        driver.get("https://soulltd.in/")
        time.sleep(3)
        driver.execute_script("window.scrollBy(0,750)")
        time.sleep(3)
        who_we_are_button = driver.find_element(By.XPATH,"//button[normalize-space()='Who we are?']")
        who_we_are_button.click()
        time.sleep(3)
        company_logo = driver.find_element(By.XPATH,"//img[@alt='Company Logo']")
        company_logo.click()
        driver.execute_script("window.scrollBy(0,750)")
        time.sleep(3)
        our_vision_button = driver.find_element(By.XPATH,"//button[normalize-space()='Our Vision & Mission']")
        our_vision_button.click()
        time.sleep(3)
        company_logo.click()
        time.sleep(2)
        driver.execute_script("window.scrollBy(0,750)")
        time.sleep(3)
        our_values_button = driver.find_element(By.XPATH,"//button[normalize-space()='Our Values']")
        our_values_button.click()
        time.sleep(2)
        company_logo.click()
        time.sleep(3)
        driver.execute_script("window.scrollBy(0,1650)")
        time.sleep(2)
        it_button = driver.find_element(By.XPATH,"//a[@href='/service/it']//div[@class='card-img']//img[@alt='#soul_it_ites_iot']")
        it_button.click()
        time.sleep(3)
        driver.back()
        time.sleep(3)
        smart_button = driver.find_element(By.XPATH,"//img[@alt='#soul_smart_infra']")
        smart_button.click()
        time.sleep(3)
        driver.back()
        ba_button = driver.find_element(By.XPATH,"//a[@href='/service/business']//div[@class='card-img']//img[@alt='#soul_it_ites_iot']")
        ba_button.click()
        time.sleep(3)
        driver.back()
        driver.execute_script("window.scrollBy(0,700)")
        time.sleep(3)
        explore_button = driver.find_element(By.XPATH,"//button[normalize-space()='Explore']")
        explore_button.click()
        time.sleep(2)
        driver.back()
        time.sleep(2)
        driver.execute_script("window.scrollBy(0,1000)")
        time.sleep(3)
        fullname = driver.find_element(By.XPATH,"//input[@placeholder='Your Full Name*']")
        fullname.send_keys("Chinmaya Kumar Nayak")
        mail = driver.find_element(By.XPATH,"//input[@placeholder='Your Email*']")
        mail.send_keys("chinmayakumar8249@gmail.com")
        contact_number = driver.find_element(By.XPATH,"//input[@placeholder='Contact Number*']")
        contact_number.send_keys(8249117340)
        write_your_message = driver.find_element(By.XPATH,"//textarea[@id='msg-text']")
        write_your_message.send_keys("This is a very nice company")
        time.sleep(3)
        about_us_button = driver.find_element(By.XPATH,"//a[@class='drop-down'][normalize-space()='About Us']")
        about_us_button.click()
        driver.execute_script("window.scrollBy(0,2700)")
        time.sleep(3)
        read_more = driver.find_element(By.XPATH,"//span[@class='readmoreBtn']")
        read_more.click()
        time.sleep(3)
        services = driver.find_element(By.XPATH,"//a[normalize-space()='Services']")
        services.click()
        time.sleep(3)
        ites = driver.find_element(By.XPATH,"//img[@alt='#soul_it_ites_iot']")
        ites.click()
        time.sleep(3)
        driver.back()
        smart_infra = driver.find_element(By.XPATH,"//img[@alt='#soul_smart_infra']")
        smart_infra.click()
        time.sleep(3)
        driver.back()
        business = driver.find_element(By.XPATH,"//img[@alt='#soul_business_advisory']")
        business.click()
        time.sleep(3)
        driver.back()
        driver.execute_script("window.scrollBy(0,1000)")
        td = driver.find_element(By.XPATH,"//p[normalize-space()='Technology and Digital Transformation']")
        td.click()
        time.sleep(2)
        es = driver.find_element(By.XPATH,"//p[normalize-space()='Education and Skill Development']")
        es.click()
        time.sleep(2)
        health = driver.find_element(By.XPATH,"//p[normalize-space()='Healthcare']")
        health.click()
        time.sleep(2)
        smart = driver.find_element(By.XPATH,"//p[normalize-space()='Smart Infrastructure']")
        smart.click()
        time.sleep(2)
        energy = driver.find_element(By.XPATH,"//p[normalize-space()='Energy, Agriculture, and Sustainable Livelihood']")
        energy.click()
        time.sleep(2)
        environment = driver.find_element(By.XPATH,"//p[normalize-space()='Environmental Sustainability and Tourism']")
        environment.click()
        time.sleep(2)
        disaster = driver.find_element(By.XPATH,"//p[normalize-space()='Disaster Management & Resilience']")
        disaster.click()
        time.sleep(2)
        products = driver.find_element(By.XPATH,"//a[@class='drop-down'][normalize-space()='Products']")
        products.click()
        time.sleep(3)
        driver.execute_script("window.scrollBy(0,250)")
        soul_care_learnmore = driver.find_element(By.XPATH,"//a[@href='/products/soul-care']//button[@class='learn-btn-product'][normalize-space()='Learn more']")
        soul_care_learnmore.click()
        time.sleep(2)
        soul_care_back_button = driver.find_element(By.XPATH,"//button[normalize-space()='Back']")
        soul_care_back_button.click()
        time.sleep(2)
        driver.execute_script("window.scrollBy(0,250)")
        time.sleep(2)
        soul_erp_learnmore = driver.find_element(By.XPATH,"//a[@href='/products/soul-erp']//button[@class='learn-btn-product'][normalize-space()='Learn more']")
        soul_erp_learnmore.click()
        time.sleep(2)
        soulerp_back = driver.find_element(By.XPATH,"//button[normalize-space()='Back']")
        soulerp_back.click()
        time.sleep(3)
        keyprojects = driver.find_element(By.XPATH,"//a[@class='drop-down'][normalize-space()='Key Projects']")
        keyprojects.click()
        time.sleep(3)
        ssc_read_more = driver.find_element(By.XPATH,"//a[@href='/key-projects/soul-smart-campus']//button[@class='btn-readMore']//span[@class='text'][normalize-space()='Read More']")
        ssc_read_more.click()
        time.sleep(2)
        driver.back()
        career = driver.find_element(By.XPATH,"//a[@class='drop-down'][normalize-space()='Career']")
        career.click()
        time.sleep(3)
        search_bar = driver.find_element(By.XPATH,"//input[@placeholder='Search job role, department, location']")
        search_bar.send_keys("jr.software engineer")
        time.sleep(3)
        applynow = driver.find_element(By.XPATH,"//div[@class='career-container']//div[1]//button[1]//a[1]")
        applynow.click()
        time.sleep(3)
        fullname = driver.find_element(By.XPATH,"//input[@placeholder='Your Full Name*']")
        fullname.send_keys("Chinmaya Kumar Nayak")
        mail = driver.find_element(By.XPATH,"//input[@placeholder='Your Email*']")
        mail.send_keys("chinmayakumar8249@gmail.com")
        number = driver.find_element(By.XPATH,"//input[@placeholder='Contact Number*']")
        number.send_keys(8249117340)
        time.sleep(3)
        back_button = driver.find_element(By.XPATH,"//button[normalize-space()='Back']")
        back_button.click()
        time.sleep(3)
        driver.execute_script("window.scrollBy(0,1000)")
        time.sleep(3)
        name = driver.find_element(By.XPATH,"//input[@placeholder='Your Full Name*']")
        name.send_keys("Chinmaya Kumar Nayak")
        mails = driver.find_element(By.XPATH,"//input[@placeholder='Your Email*']")
        mails.send_keys("chinmayakumar8249@gmail.com")
        numbers = driver.find_element(By.XPATH,"//input[@placeholder='Contact Number*']")
        numbers.send_keys(8249117340)
        time.sleep(3)
        get_in_touch = driver.find_element(By.XPATH,"//button[normalize-space()='Get in Touch']")
        get_in_touch.click()
        time.sleep(3)
        myname = driver.find_element(By.XPATH,"//input[@placeholder='Your Full Name*']")
        myname.send_keys("Chinmaya Kumar Nayak")
        mymail = driver.find_element(By.XPATH,"//input[@placeholder='Your Email*']")
        mymail.send_keys("chinmayakumar8249@gmail.com")
        mynumber = driver.find_element(By.XPATH,"//input[@placeholder='Contact Number*']")
        mynumber.send_keys(8249117340)
        wym = driver.find_element(By.XPATH,"//textarea[@id='msg-text']")
        wym.send_keys("I need your erp software")
        time.sleep(3)
        careers_page = driver.find_element(By.XPATH,"//a[normalize-space()='Careers Page']")
        careers_page.click()
        time.sleep(3)
        driver.back()
        time.sleep(3)
        sur = driver.find_element(By.XPATH,"//a[normalize-space()='Submit Your Resume']")
        sur.click()
        time.sleep(3)
        driver.back()

a = Test_soulwebsite()
a.automate()



